#include "qp/portfolio/portfolio.hpp"
#include <cmath>
namespace qp::portfolio {
static Result<void> validate_money(double x,const char* label){ if(!std::isfinite(x)||x<0.0) return Err(Error{ErrorCode::InvalidArgument,label}); return Ok(); }
Portfolio::Portfolio(double initial_cash): cash_(initial_cash){ if(!std::isfinite(initial_cash)||initial_cash<0.0) throw std::invalid_argument("initial cash must be finite and non-negative"); }
Position Portfolio::position(const Symbol& s) const { auto it=positions_.find(s); return it==positions_.end()?Position{Quantity{0.0}, Price{0.0}}:it->second; }
Result<void> Portfolio::buy(const Symbol& s, Quantity q, Price p, double fee){ execution::Fill f{execution::OrderId{1},s,execution::OrderSide::Buy,Timestamp{},q,p,fee,0.0}; auto r=apply_fill(f); if(!r) return Err(r.error()); return Ok(); }
Result<void> Portfolio::sell(const Symbol& s, Quantity q, Price p, double fee){ execution::Fill f{execution::OrderId{1},s,execution::OrderSide::Sell,Timestamp{},q,p,fee,0.0}; auto r=apply_fill(f); if(!r) return Err(r.error()); return Ok(); }
Result<TradeLedgerEntry> Portfolio::apply_fill(const execution::Fill& fill){ auto fok=fill.validate(); if(!fok) return Err<TradeLedgerEntry>(fok.error()); auto feeok=validate_money(fill.commission,"fee must be finite and non-negative"); if(!feeok) return Err<TradeLedgerEntry>(feeok.error()); auto& pos=positions_[fill.symbol]; double realized=0.0; if(fill.side==execution::OrderSide::Buy){ double cost=fill.quantity.value*fill.price.value+fill.commission; if(cost>cash_) return Err<TradeLedgerEntry>(Error{ErrorCode::InvalidArgument,"insufficient cash"}); double old_qty=pos.quantity.value; double new_qty=old_qty+fill.quantity.value; pos.average_price=Price{new_qty>0.0 ? (old_qty*pos.average_price.value + fill.quantity.value*fill.price.value)/new_qty : 0.0}; pos.quantity=Quantity{new_qty}; cash_-=cost; }
 else { if(fill.quantity.value>pos.quantity.value) return Err<TradeLedgerEntry>(Error{ErrorCode::InvalidArgument,"cannot sell more than current long position"}); realized=(fill.price.value-pos.average_price.value)*fill.quantity.value-fill.commission; realized_pnl_+=realized; pos.quantity=Quantity{pos.quantity.value-fill.quantity.value}; cash_ += fill.quantity.value*fill.price.value-fill.commission; if(pos.quantity.value==0.0) pos.average_price=Price{0.0}; }
 TradeLedgerEntry e{fill,cash_,pos.quantity,pos.average_price,realized}; ledger_.push_back(e); return Ok(e); }
double Portfolio::equity(const std::map<Symbol,Price>& marks) const { double e=cash_; for(const auto& [s,pos]:positions_){ auto it=marks.find(s); if(it!=marks.end()) e += pos.quantity.value*it->second.value; } return e; }
Result<PortfolioSnapshot> Portfolio::snapshot(Timestamp ts,const std::map<Symbol,Price>& marks) const { double gross=0.0, net=0.0, unreal=0.0; for(const auto& [s,pos]:positions_){ if(pos.quantity.value==0.0) continue; auto it=marks.find(s); if(it==marks.end()) return Err<PortfolioSnapshot>(Error{ErrorCode::InvalidArgument,"missing mark for open position",s.value}); if(!it->second.is_positive()) return Err<PortfolioSnapshot>(Error{ErrorCode::InvalidArgument,"invalid mark price",s.value}); double mv=pos.quantity.value*it->second.value; gross+=std::abs(mv); net+=mv; unreal+=(it->second.value-pos.average_price.value)*pos.quantity.value; } return Ok(PortfolioSnapshot{ts,cash_,gross,net,cash_+net,realized_pnl_,unreal}); }
}
