#include "qp/backtest/backtest_config.hpp"
#include <sstream>
#include <cmath>
namespace qp::backtest { Result<BacktestRunConfig> backtest_config_from_flat_config(const Config& c){ BacktestRunConfig cfg; if(auto v=c.get("schema_version")){ cfg.schema_version=std::string(*v); if(cfg.schema_version!="qp.backtest.config.v1") return Err<BacktestRunConfig>(Error{ErrorCode::ConfigurationError,"unsupported schema_version"}); } if(auto v=c.get("run.id")) cfg.run_id=std::string(*v); if(auto v=c.get("run.output_dir")) cfg.output_dir=std::string(*v); if(auto v=c.get("data.path")) cfg.data_path=std::string(*v); else return Err<BacktestRunConfig>(Error{ErrorCode::ConfigurationError,"missing data.path"}); if(c.get("portfolio.initial_cash")){ auto v=c.get_double("portfolio.initial_cash"); if(!v) return Err<BacktestRunConfig>(v.error()); cfg.initial_cash=v.value(); } if(c.get("strategy.buy_threshold")){ auto v=c.get_double("strategy.buy_threshold"); if(!v) return Err<BacktestRunConfig>(v.error()); cfg.buy_threshold=v.value(); } if(c.get("strategy.sell_threshold")){ auto v=c.get_double("strategy.sell_threshold"); if(!v) return Err<BacktestRunConfig>(v.error()); cfg.sell_threshold=v.value(); } if(c.get("execution.fee_per_trade")){ auto v=c.get_double("execution.fee_per_trade"); if(!v) return Err<BacktestRunConfig>(v.error()); cfg.fee_per_trade=v.value(); } if(c.get("execution.slippage_bps")){ auto v=c.get_double("execution.slippage_bps"); if(!v) return Err<BacktestRunConfig>(v.error()); cfg.slippage_bps=v.value(); } if(auto v=c.get("portfolio.base_currency")) cfg.base_currency=std::string(*v); if(cfg.run_id.empty()) return Err<BacktestRunConfig>(Error{ErrorCode::ConfigurationError,"run.id cannot be empty"});
 if(cfg.data_path.empty()) return Err<BacktestRunConfig>(Error{ErrorCode::ConfigurationError,"data.path cannot be empty"});
 if(!std::isfinite(cfg.initial_cash) || cfg.initial_cash<=0.0) return Err<BacktestRunConfig>(Error{ErrorCode::ConfigurationError,"portfolio.initial_cash must be finite and positive"});
 if(!std::isfinite(cfg.buy_threshold) || !std::isfinite(cfg.sell_threshold)) return Err<BacktestRunConfig>(Error{ErrorCode::ConfigurationError,"strategy thresholds must be finite"});
 if(!std::isfinite(cfg.fee_per_trade) || cfg.fee_per_trade<0.0) return Err<BacktestRunConfig>(Error{ErrorCode::ConfigurationError,"execution.fee_per_trade must be finite and non-negative"});
 if(!std::isfinite(cfg.slippage_bps) || cfg.slippage_bps<0.0) return Err<BacktestRunConfig>(Error{ErrorCode::ConfigurationError,"execution.slippage_bps must be finite and non-negative"});
 return Ok(cfg); }
Result<BacktestRunConfig> load_backtest_run_config(const std::filesystem::path& path){ auto cfg=load_flat_json_config(path); if(!cfg) return Err<BacktestRunConfig>(cfg.error()); return backtest_config_from_flat_config(cfg.value()); }
std::string effective_config_json(const BacktestRunConfig& c){ std::ostringstream o; o<<"{\n  \"schema_version\": \""<<c.schema_version<<"\",\n  \"run.id\": \""<<c.run_id<<"\",\n  \"run.output_dir\": \""<<c.output_dir.string()<<"\",\n  \"data.path\": \""<<c.data_path.string()<<"\",\n  \"portfolio.initial_cash\": "<<c.initial_cash<<",\n  \"strategy.buy_threshold\": "<<c.buy_threshold<<",\n  \"strategy.sell_threshold\": "<<c.sell_threshold<<",\n  \"execution.fee_per_trade\": "<<c.fee_per_trade<<",\n  \"execution.slippage_bps\": "<<c.slippage_bps<<"\n}\n"; return o.str(); } }
