#include "qp/backtest/report.hpp"
#include "qp/features/returns.hpp"
#include "qp/portfolio/portfolio.hpp"
#include "qp/signals/momentum.hpp"
#include <map>
namespace qp::backtest { Result<BacktestReport> run_configured_momentum_backtest(const std::vector<data::OhlcvBar>& bars,const BacktestRunConfig& cfg){ if(bars.empty()) return Err<BacktestReport>(Error{ErrorCode::InvalidArgument,"backtest requires bars"}); portfolio::Portfolio pf(cfg.initial_cash); features::SimpleReturn ret; signals::MomentumSignal model(signals::MomentumConfig{"simple_return",cfg.buy_threshold,cfg.sell_threshold,"momentum"}); std::map<Symbol,Timestamp> last_end; std::map<Symbol,Price> marks; BacktestReport report; report.run_id=cfg.run_id; report.config=cfg; report.initial_cash=cfg.initial_cash; std::uint64_t oid=1; for(const auto& bar:bars){ auto ok=bar.validate(); if(!ok) return Err<BacktestReport>(ok.error()); auto it=last_end.find(bar.symbol); if(it!=last_end.end() && bar.start<it->second) return Err<BacktestReport>(Error{ErrorCode::InvalidData,"bars must be sorted and non-overlapping per symbol",bar.symbol.value}); last_end[bar.symbol]=bar.end; marks[bar.symbol]=bar.close; ++report.bars_seen; auto fv=ret.update(data::MarketData{bar}); if(!fv) return Err<BacktestReport>(fv.error()); if(fv.value()){ auto sig=model.update(*fv.value()); if(sig){ auto pos=pf.position(bar.symbol); if(sig->side==signals::SignalSide::Buy && pos.quantity.value==0.0){ execution::Fill f{execution::OrderId{oid++},bar.symbol,execution::OrderSide::Buy,bar.end,Quantity{1.0},Price{bar.close.value*(1.0+cfg.slippage_bps/10000.0)},cfg.fee_per_trade,cfg.slippage_bps/10000.0*bar.close.value}; auto e=pf.apply_fill(f); if(!e) return Err<BacktestReport>(e.error()); report.fills.push_back(f); report.ledger.push_back(e.value()); }
          if(sig->side==signals::SignalSide::Sell && pos.quantity.value>0.0){ execution::Fill f{execution::OrderId{oid++},bar.symbol,execution::OrderSide::Sell,bar.end,pos.quantity,Price{bar.close.value*(1.0-cfg.slippage_bps/10000.0)},cfg.fee_per_trade,cfg.slippage_bps/10000.0*bar.close.value*pos.quantity.value}; auto e=pf.apply_fill(f); if(!e) return Err<BacktestReport>(e.error()); report.fills.push_back(f); report.ledger.push_back(e.value()); }
        } }
      auto snap=pf.snapshot(bar.end,marks); if(!snap) return Err<BacktestReport>(snap.error()); report.equity_curve.push_back(EquityPoint{bar.end,snap.value().equity,snap.value().cash,snap.value().gross_exposure,snap.value().net_exposure}); }
 report.trades=report.fills.size(); report.cash=pf.cash(); auto snap=pf.snapshot(bars.back().end,marks); if(!snap) return Err<BacktestReport>(snap.error()); report.final_equity=snap.value().equity; for(const auto& [sym,px]:marks) report.positions[sym]=pf.position(sym); return Ok(report); } }
