name: ci
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
jobs:
  bare-linux:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        preset: [debug, release, asan, ubsan, ci]
    steps:
      - uses: actions/checkout@v4
      - run: cmake --version && c++ --version
      - run: cmake --preset ${{ matrix.preset }}
      - run: cmake --build --preset ${{ matrix.preset }} --parallel 2
      - run: ctest --preset ${{ matrix.preset }} --output-on-failure
